export default function TermsOfServiceContent() {
    return (
        <div className="mx-auto max-w-7xl px-8 py-12">
            <h1 className="text-3xl text-black font-bold text-center sm:text-4xl py-16">Terms Of Service</h1>
            <p className="text-lg text-gray-500">These Terms of Service (“Terms” or “Terms of Service”) apply to any visitors of <a href='.#.' className="text-blue-600 font-bold">https://registate.com/ </a>(the “Website”), customers and those who show interest in ordering the services of Reggae Registered Agents Inc. (“Reggae” or “Registate” or the “Company” or “we”) as well as its affiliates.  In these Terms, the words “you” and “your” refer to each customer and Website visitor. These Terms govern the terms and conditions of services we offer and your use of the Website. By using our Services and the Website, you agree to be bound by these Terms as well as our Privacy Policy, as it may be amended. If you do not agree with these Terms, or the terms contained in our Privacy Policy, please discontinue your use of the Website immediately. We may revise these Terms of Service at any time without notice to you. If you have any questions about these Terms, please contact us. Please read these Terms carefully before using the Website.    </p>
            <h2 className="py-8 text-2xl sm:text-3xl text-black font-bold">Disclaimer</h2>
            <p className="text-lg text-gray-500">Registate is a document filing service company, not a law firm. We do not provide you with legal advice or legal counsel under any circumstances. Nothing herein is intended as legal advice. If you feel legal advice is needed, we urge you to contact an attorney. Whether by chat, e-mail or any other use of this Website or transmission of this information is not intended to create, and receipt of this information does not constitute, an attorney-client relationship.
                The information presented on the Website, chat, e-mail or any other form of communication is made available solely for general information purposes to provide certain characteristics, and advantages and disadvantages of conducting business in Delaware. Registate does not warrant that the Website or any content, service or feature of the Website will be error-free or fully accurate, or that any defects will be corrected, or that your use of the Website will provide specific results. You assume total responsibility for your use of the Website and any linked sites at your own risk. Please note that all information provided on the Website is subject to change without notice.
                <br />
                <br />
                We disclaim all liability and responsibility arising from any reliance placed on such materials by you or any other visitor to the Website, or by anyone who may be informed of any of its contents. The above disclaimer applies to any damages, liability or injuries caused by any failure of performance, error, omission, interruption, deletion, defect, delay in operation or transmission, computer virus, communication line failure, theft or destruction of or unauthorized access to, alteration of, or use, whether for breach of contract, tort, negligence or any other cause of action.
                <br />
                <br />
                We may make changes to any products or services offered on the Website, or to the applicable prices for any such products or services, at any time, without notice. The materials on the Website with respect to products and services may be out of date, and Registate makes no commitment to update the materials on the Website with respect to such products and services.</p>
            <h3 className="py-8 pl-8 text-xl sm:text-2xl text-black font-bold">1. Services and Filings</h3>
            <p className="text-lg text-gray-500">Receiving Service of Process<br /><br />
                As your registered agent, we are to accept legal documents on your behalf and convey them to the contact person whose contact information you have provided. You hereby authorize us to receive service of process and legal documents of any kind (“Legal Documents”) on your behalf as well as opening, scanning, uploading and transmitting the Legal Documents to you. Registered agent services are limited to the receipt of service of process as well as the receipt and forwarding of Legal Documents, and do not include the receipt of any general or regular mail or other items. Accordingly, we do not assume liability to you, or any third party, for loss of mail or other items which are not Legal Documents.</p>
            <h3 className="py-8 text-xl sm:text-2xl text-black font-bold">Non-Legal Documents.</h3>
            <p className="text-lg text-gray-500">All other documents that do not fall within the definition of Legal Documents are to be deemed “Non-Legal Documents.” Depending on which services you have purchased from us, there may be a limit on how many Non-Legal Documents will be accepted by our office on your company’s behalf without incurring additional fees.You may be charged for any physical document forwarding requests that exceed your purchased limits. You agree to pay the fees that we post to your account related to any Non-Legal Documents which we receive on your company’s behalf in excess of your purchased service limit. This includes any fees posted in relation to requests to forward physical documents.</p>
            <h3 className="py-8 text-xl sm:text-2xl text-black font-bold">Electronic Records and Signatures</h3>
            <p className="text-lg text-gray-500">In order to fulfill orders, we often need to file documents that are signed either electronically or in wet-signature form. You will receive a signature request from our customer service representatives once you put in any order.</p>
            <h3 className="py-8 text-xl sm:text-2xl text-black font-bold">Accurate Information</h3>
            <p className="text-lg text-gray-500">You agree that you are solely responsible for the accuracy, quality, integrity, legality, reliability, and appropriateness of your information that is provided to us. You agree that the accuracy of filings which we make on your behalf depends on the information you provide and you agree to promptly notify us when any of your information changes.</p>
            <h3 className="py-8 text-xl sm:text-2xl text-black font-bold">Auto-Payments</h3>
            <p className="text-lg text-gray-500"> <h3 className="py-8 text-xl sm:text-2xl text-black font-bold">Accurate Information</h3>
                <p className="text-lg text-gray-500">You agree that you are solely responsible for the accuracy, quality, integrity, legality, reliability, and appropriateness of your information that is provided to us. You agree that the accuracy of filings which we make on your behalf depends on the information you provide and you agree to promptly notify us when any of your information changes.</p></p>
            <h3 className="py-8 pl-8 text-xl sm:text-2xl text-black font-bold">2. Your Responsibilities</h3>
            <p className="text-lg text-gray-500">You are responsible for:</p>
            <ul className="text-lg text-gray-500 list-disc pl-8">
                <li>Making all arrangements necessary for you to access to the Website (g., appropriate hardware and software).</li>
                <li>Ensuring that all persons who access the Website through your internet connection are aware of these Terms and comply with them.</li>
                <li>If you register on the Website, protecting the confidentiality of your username and password used to access your account on the Website.</li>
                <li>Ensuring that any person(s) using your account are not violating these Terms, any other agreement you may have with the Company, or any provision of federal or state law or regulation.</li>
                <li>Maintaining accurate contact information for your account; this is particularly important for registered agent clients of the Company, as Delaware law requires that a registered agent maintain current and correct contact information for its clients, and provides that a failure to do so may result in our resignation as registered agent, among other things</li>
                <li>Be aware of this and other relevant Terms of Uses within the Website; to be compliant to this Terms
                    Not to attempt to gain unauthorized access to any portion or feature of the Website, or any other systems or networks connected to the Website or to any of the services offered on or through the Website, by hacking, password “mining” or any other illegitimate means. You may not to use any device, software or routine to interfere or attempt to interfere with the proper working of the Website or any transaction being conducted on the Site, or with any other person’s use of the Website. You may not use the Website or any Content for any purpose that is unlawful or prohibited by these Terms of Services, or to solicit the performance of any illegal activity or other activity which infringes the rights of the Company or others.</li>
            </ul>
            <h3 className="py-8 pl-8 text-xl sm:text-2xl text-black font-bold">3. Responsibilities and Rights of Registate</h3>
            <p className="text-lg text-gray-500">Registate takes reasonable steps to maintain security but please note that we cannot make an absolute guarantee of system security. If you have reason to believe system security has been breached, contact us immediately by email for help.
                <br /><br />
                If we suspect your account has been used for an unauthorized, illegal or criminal purpose, we are hereby authorized to share information about you and your account with the relevant law enforcement agencies. Registate also reserves the right at all times to disclose any information that the Company deems necessary to comply with any applicable law, regulation, legal process or governmental request. Registate also may disclose your information when the Company determines that applicable law requires or permits such disclosure, including exchanging information with other companies and organizations for fraud protection purposes.
                <br /><br />
                We reserve the right to temporarily or permanently shut down or remove access to all or part of the Website, and any service or material we provide on the Website, in our sole discretion, with or without notice. We will not be liable to you if, for any reason, all or any part of the Website is unavailable at any time or for any period. From time to time, we may restrict access to some parts of the Website, or the entire Website, to users, including registered users.  This may occur in the process of servicing the Website, amending all or a portion of the Website’s content, or adding additional functionality and features to the Website, among other things.</p>
            <h3 className="py-8 pl-8 text-xl sm:text-2xl text-black font-bold">4. Termination</h3>
            <p className="text-lg text-gray-500">Registate reserves the right to refuse service, terminate account, cancel user access, use of the Website, and remove any communication transmitted by you and information stored/sent/received at any time in its sole discretion. Reasons for termination may include, but are not limited to: i) you fail to provide accurate, complete and current information for your order; ii) if we are unable to locate you after reasonable efforts are made; iii) you fail to pay for your Service; or iv) suspected illegal activity.
                <br /><br />
                You may terminate your use of our services upon five (5) business days written notice by you at info@registate.com of your intent to terminate these Terms. Upon termination of these Terms, all rights granted to you will automatically terminate and immediately revert to Registate and its licensors. Upon termination of services, you may be required to pay any past-due balances related to such services, unless otherwise specified in this Terms.
                <br /><br />
                If we receive any Legal Documents on your behalf after the termination of registered agent services, we will send an email notice to the last known email address regarding the received Legal Documents. If you want to view a Legal Document, you will need to renew your service with us, pay any fees incurred prior to cancellation or pay a per document fee in order to view the Legal Document. Once you take one of these actions, we will make the Legal Document available to you. We are not liable or responsible for forwarding you documents of any kind after our service relation is terminated or cancelled. You agree to hold Registate and its offıcers, directors, employees, and agents will be held harmless from any third party claim arising out of a delay or failure of you to receive Legal Documents after your registered agent service has been terminated.</p>
            <h3 className="py-8 pl-8 text-xl sm:text-2xl text-black font-bold">5. Ownership</h3>
            <p className="text-lg text-gray-500">This Website is owned and operated by Reggae Registered Agents Inc. All rights, titles, posts, texts, graphics, user interfaces, visual interfaces, images, trademarks, logos, artwork (collectively, “Materials”) on the Website is owned, controlled or licensed by or to Reggae Registered Agents Inc., or our third party developers and vendors. Except as otherwise expressly provided in these Terms of Service, no part of the Website and none of the Materials may be copied, reproduced, republished, uploaded, posted, publicly displayed, encoded, translated, transmitted or distributed in any way to any other computer, server, Website or other medium for publication or distribution or for any commercial enterprise, without Reggae’s express prior written consent.</p>
            <h3 className="py-8 pl-8 text-xl sm:text-2xl text-black font-bold">6. Copyright, Trademark, Patent</h3>
            <p className="text-lg text-gray-500">All Website design, text, graphics, the selection and arrangement thereof, Copyright © Registate ALL RIGHTS RESERVED.
                The Website and its entire contents, features, and functionality (including but not limited to all information, software, text, displays, images, video and audio, and the design, selection and arrangement thereof), are owned by the Company, its licensors or other providers of such material, the foregoing materials are protected by United States and international copyright, trademark, patent, trade secret and other intellectual property or proprietary rights laws.</p>
            <h3 className="py-8 pl-8 text-xl sm:text-2xl text-black font-bold">7. Privacy</h3>
            <p className="text-lg text-gray-500">We respect your privacy and permit you to control the treatment of your personal information. The Company’s Privacy Policy applies to use of this Website, and its terms are made a part of these Terms of Use by this reference. For our services, you may be asked to provide personal information in a form or similar document or through any forms of communication.
                By using the Website, you acknowledge and agree that Internet transmissions are never completely private or secure. You understand that any message or information you send to the Website may be read or intercepted by others, even if there is a special notice that a particular transmission (for example, credit card information) is encrypted. </p>
            <h3 className="py-8 pl-8 text-xl sm:text-2xl text-black font-bold">8. Use of Forms</h3>
            <p className="text-lg text-gray-500">In some of our services, we make certain legal forms available to our customers for their convenience. Users of such forms are hereby notified that any use of such forms may impact the legal rights and obligations of the parties involved. Nothing within those forms should be construed as legal advice. Any user of our forms acknowledges the risk of using template forms and the user voluntarily assumes that risk by using our forms. Users of such forms agree that they will not consider the contents of any form, website, or communication with Registate as valid substitutions to seeking legal advice from a qualified legal professional. We disclaim any liability which may result from the use or misuse of our freely available forms.</p>
            <h3 className="py-8 pl-8 text-xl sm:text-2xl text-black font-bold">9. Limitation of Liability and Indemnification</h3>
            <p className="text-lg text-gray-500">EXCEPT AS PROHIBITED BY LAW, REGISTATE AND ITS OFFICERS, DIRECTORS, EMPLOYEES, AND AGENTS WILL BE HELD HARMLESS FOR ANY INDIRECT, PUNITIVE, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGE, HOWEVER IT ARISES (INCLUDING ATTORNEYS’ FEES AND ALL RELATED COSTS AND EXPENSES OF LITIGATION AND ARBITRATION, OR AT TRIAL OR ON APPEAL, IF ANY, WHETHER OR NOT LITIGATION OR ARBITRATION IS INSTITUTE), WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE, OR OTHER TORTIOUS ACTION, OR ARISING OUT OF OR IN CONNECTION WITH THIS AGREEMENT, INCLUDING WITHOUT LIMITATION ANY CLAIM FOR PERSONAL INJURY OR PROPERTY DAMAGE, ARISING FROM THIS TERMS AND ANY VIOLATION BY YOU OF ANY FEDERAL, STATE, OR LOCAL LAWS, STATUTES, RULES, OR REGULATIONS, EVEN IF REGISTATE HAS BEEN PREVIOUSLY ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. EXCEPT AS PROHIBITED BY LAW, IF THERE IS LIABILITY FOUND ON THE PART OF REGISTATE, IT WIILL BE LIMITED TO THE AMOUNT PAID FOR THE SERVICES, AND UNDER NO CIRCUMSTANCES WILL THERE BE CONSEQUENTIAL OR PUNITIVE DAMAGES.</p>
            <h3 className="py-8 pl-8 text-xl sm:text-2xl text-black font-bold">10. No Warranty</h3>
            <p className="text-lg text-gray-500">THE WEBSITE AND ALL MATERIALS, DOCUMENTS OR FORMS PROVIDED ON OR THROUGH YOUR USE OF THE WEBSITE OR THROUGH COMMUNICATION ARE PROVIDED ON AN “AS IS” AND “AS AVAILABLE” BASIS. TO THE FULLEST EXTENT PERMITTED BY LAW, REGISTATE EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT.
                <br /><br />
                REGISTATE MAKES NO WARRANTY THAT: (A) THE WEBSITE OR THE MATERIALS WILL MEET YOUR REQUIREMENTS; (B) THE WEBSITE OR THE MATERIALS WILL BE AVAILABLE ON AN UNINTERRUPTED, TIMELY, SECURE OR ERROR-FREE BASIS; (C) THE RESULTS THAT MAY BE OBTAINED FROM THE USE OF THE WEBSITE OR THE MATERIALS OFFERED THROUGH THE SITE OR APPLICATIONS, WILL BE ACCURATE OR RELIABLE; OR (D) THE QUALITY OF ANY PRODUCTS, SERVICES, INFORMATION OR OTHER MATERIAL PURCHASED OR OBTAINED BY YOU THROUGH THE WEBSITE OR IN RELIANCE ON THE MATERIALS WILL MEET YOUR EXPECTATIONS.
                <br /><br />
                OBTAINING ANY MATERIALS THROUGH THE USE OF THE WEBSITE IS DONE AT YOUR OWN DISCRETION AND AT YOUR OWN RISK. REGISTATE SHALL HAVE NO RESPONSIBILITY FOR ANY DAMAGE TO YOUR COMPUTER SYSTEM OR LOSS OF DATA THAT RESULTS FROM THE DOWNLOAD OF ANY CONTENT, MATERIALS, INFORMATION OR SOFTWARE. </p>
            <h3 className="py-8 pl-8 text-xl sm:text-2xl text-black font-bold">11. Minors</h3>
            <p className="text-lg text-gray-500">Minors are not eligible to use this Website. We kindly request you not to provide us with personal information of such individuals. If you are under the age of eighteen (18), please do not provide any information and cease your activities with this website.</p>
            <h3 className="py-8 pl-8 text-xl sm:text-2xl text-black font-bold">12. Geographic Restrictions</h3>
            <p className="text-lg text-gray-500">No Services can be provided to a national or resident of Belarus, Cuba, Eritrea, Iran, North Korea, Syria, Venezuela, or any other country to which the U.S. has embargoed goods or prohibited commercial transactions (“Restricted Countries”),
                to anyone on the U.S. Treasury Department’s Office of Foreign Asset Control (“OFAC”) lists.
                By using the Website and ordering our services, you represent and warrant that you are not located in, under the control of, or a national or resident of a Restricted Country and are not currently named on any sanctions list maintained by OFAC.</p>
            <h3 className="py-8 pl-8 text-xl sm:text-2xl text-black font-bold">13. Governing Law and Venue</h3>
            <p className="text-lg text-gray-500">You agree that all matters relating to your access to or use of the Site, including all disputes, will be governed by the laws of the United States and by the laws of the State of Delaware without regard to its conflicts of laws provisions. You agree to the personal jurisdiction by and venue in the state and federal courts in Delaware, and waive any objection to such jurisdiction or venue. </p>
            <h3 className="py-8 pl-8 text-xl sm:text-2xl text-black font-bold">14. Severability</h3>
            <p className="text-lg text-gray-500">In the event any of the provisions of these Terms are deemed to be unenforceable by a court of law, such provisions shall be limited or eliminated to the minimum extent necessary so that these Terms shall otherwise remain in full force and effect.</p>
            <h3 className="py-8 pl-8 text-xl sm:text-2xl text-black font-bold">15. Entire Agreement</h3>
            <p className="text-lg text-gray-500">These Terms and the terms of our Privacy Policy constitute the entire agreement between you and us with respect to our services and this Website.</p>
            <h3 className="py-8 pl-8 text-xl sm:text-2xl text-black font-bold">16. No Waiver</h3>
            <p className="text-lg text-gray-500">No waiver of any provision or any right granted hereunder will be effective unless set forth in a written instrument signed by the waiving party. No waiver by either party of any breach or default hereunder shall be deemed a waiver of any subsequent breach or default.</p>
            <h3 className="py-8 pl-8 text-xl sm:text-2xl text-black font-bold">17. Assignment</h3>
            <p className="text-lg text-gray-500">You may assign your rights and obligations under these Terms provided we receive prior written notice of, and approve of, such assignment. We will not unreasonably withhold our approval. We may assign our rights or obligations to any successor in interest of any business associated with the Services.
BY USING REGISTATE’S SERVICES OR ACCESSING THIS WEBSITE, YOU ACKNOWLEDGE THAT YOU HAVE READ THESE TERMS OF USE AND AGREE TO BE BOUND BY THEM.</p>
        </div>
    )
}
