export default function PolicyContent() {
    return (
        <div className="mx-auto max-w-7xl px-8 py-12">
            <h1 className="text-3xl text-black font-bold text-center sm:text-4xl py-16">Privacy Policy</h1>
            <p className="text-lg text-gray-500">We, as Registate, take your privacy and personal information seriously and place great importance to be transparent on how we use the personal information we collect from and about you.<br /><br />
                In this Policy, we describe what information we collect, how we use and maintain personal information we collect through our website or by other means (including via telephone) and how it may be disclosed, as well as protections for our customers’, prospective customers’ and visitors’ personal information.<br /><br />
                This Policy, alongside our Terms of Use and Terms of Service, governs your use of our services. You accept this Policy and its terms by using Registate’s services.</p>
            <h3 className="py-8 text-xl sm:text-2xl text-black font-bold">Information We Collect</h3>
            <p className="text-lg text-gray-500">We collect and retain several types of personal information about our customers, prospective customers and visitors of our website. The type of information we collect depends on (i) the interaction we have with you (whether by just simply browsing our website or filling out the forms we provide, etc.), (ii) the types of services you consider or purchase, (iii) and what you choose to share with us. In many cases, you can choose whether to provide us with personal information, however, if you choose not to, please note that you may not receive full functionality from our services.<br /><br />
                We mostly collect the following categories of information about consumers, some of which may be collected or maintained in a manner such that it can be considered personal information:<br /><br />
                Identifiers: To render our services properly, we may collect personal information such as name, address, telephone number, email address, social security number, Federal Tax Identification number, account numbers, user name, Internet Protocol address (“IP address”) and other online identifiers.<br /><br />
                Business Information: We may be required to collect information such as legal entity name, business entity or filing, registered agent, officers, directors, managers or members of an entity, communications contact and other business related information.<br /><br />
                Internet Information: To maximize the effectiveness of our services, we may collect information concerning network activities, including browsing history, search history, information about the device you are using to access our website, information regarding your interaction with our website, browser settings, operating systems, referring/exit pages, and clickstream data.<br /><br />
                Audio & Communication Information: In case when you call us, we may record the telephone conversation to improve our customer services. We also retain the email exchanges between you and us.<br /><br />
                Other Types of Information: We may collect information concerning where our customers reside or are otherwise located. We may also collect financial information including bank account numbers. We often use third-party payment systems to provide payment processing (i.e. Stripe). Such third-party payment systems may require payment information such as credit/debit card number. Please note that such third-party payment systems have their own privacy policies they implement for their users. Registate or its affiliates cannot be held responsible for the actions by such third-party payment services that infringe privacy.
            </p>
            <h3 className="py-8 text-xl sm:text-2xl text-black font-bold">How Do We Collect Data?</h3>
            <p className="text-lg text-gray-500">We receive information about our customers from several sources. We may collect personal information through your interaction with our website, either directly from you when you provide information to us by filling in forms, or automatically as you navigate through the website. We can also receive information through text and other electronic messages (including the live chat feature) between you and our customer service.
                <br /><br />
                Additionally, we collect information by e-mails sent to our email addresses with “registate” email domain names. Please note that, depending on the services you purchase, we may request additional information by email to complete the orders.
                <br /><br />
                Lastly, we can receive information from/through third party sources, including (but not limited to), (i) person(s) arranging our services for you such as your employer, (ii) partners and service providers who work with you in relation to your service (iii) and, publicly available sources such as public websites, open government databases or other data open to the public.</p>
            <h3 className="py-8 text-xl sm:text-2xl text-black font-bold">How We Use the Information We Collect</h3>
            <p className="text-lg text-gray-500"> We use personal information to provide and improve our services and for other purposes that are in our legitimate interests including compliance purposes. Where we rely on legitimate interests as a lawful ground for processing your personal information, we balance those interests with your interests, fundamental rights and freedoms. Apart from providing services, we collect personal information:</p>
            <ul className="text-lg text-gray-500 list-disc pl-8">
                <li>To respond inquiries from customers and prospective customers with information on our services that is requested from us.</li>
                <li>To present our website and its contents to you.</li>
                <li>To improve improve our existing services and to develop new services</li>
                <li>To ensure the security of our networks and to detect fraud or other suspicious activities.</li>
                <li>To fulfill our obligations arising from any contracts entered into between you and us.</li>
                <li>To fulfill legal compliance obligations (requests from courts, law enforcement agencies, regulatory agencies, and other public and government authorities, including where they are outside your country of residence)</li>
                <li>To use in marketing to our current and prospective customers.
We retain your personal information as long as we are providing our services to you. We may still retain personal information even after the order of service is completed or closing your account with us, for the purpose and to the extent necessary to comply with our legal, regulatory, tax, accounting, financial and similar obligations. Such retention will be in accordance with the applicable law, complying with any retention obligations and limitation periods.</li>
            </ul>
            <h3 className="py-8 text-xl sm:text-2xl text-black font-bold">Disclosure of Information</h3>
            <p className="text-lg text-gray-500"> We do not sell or distribute any of the information we collect you provide to us. We may share and disclose personal information to following third-parties for the following purposes:<br/><br/>
            Service Providers: We may share information about our customers with the service providers who assist us with completing the orders.  Such service providers are not authorized to use the information for any other purpose other than providing services to us or to you. We review and inspect the conduct of our service providers on a regular basis whether they are in compliance with our privacy policy.<br/><br/>
            Business Partners and Affiliates: We may share information with our business partners and affiliates in limited circumstances with your consent.  If you are interested in an offer made by one of our business partners, we may provide information about you in connection with the offer you have chosen.  In addition, when you purchase a service from us that is bundled with another service offered by one of our business partners, we will share information about you with those business partners so that they can provide you with the services included with your purchase.  These business partners are not authorized to use the information for their own marketing purposes without asking for your consent. In an event of a merger, acquisition or transfer, your personal information may be transferred to the successor entity. You shall be notified and be provided with an option to opt-out from such transfer.<br/><br/>
            Your Associates: We may provide information about you to your authorized contacts and associates. We will ask for your authorization before providing such information to such a third-party person.<br/><br/>
            Governmental Bodies: We may, and usually we must, share information about our customers with governmental bodies in order to fulfill the services purchased by our customers.  Please note that certain personal information may become public record once the information is filed with the government entities. For instance, the Secretary of State may publish such information to its website or provide this information to third parties for a fee.<br/><br/>
            Required by Law: We may disclose customer information if it is required by law, for instance in the form of subpoena, lawful request by a public/regulatory authority, or similar legal process, and when we believe in good faith that disclosure is necessary to protect our rights, protect your safety or the safety of others, investigate fraud, or respond to a legal request.<br/><br/>
            Please note that communication with Registate is not intended to create an attorney-client relationship. As Registate is not a law firm, any information  shared with, transferred or communicated to us is not considered privileged client-attorney information.
            </p>
            <h3 className="py-8 text-xl sm:text-2xl text-black font-bold">Security</h3>
            <p className="text-lg text-gray-500">We are committed to make certain that our servers and connections are equipped with the latest encryption and security devices. We strive to make all appropriate and reasonable effort to safeguard and protect personal information from any loss, misuse, unauthorized access, alteration and destruction. Access to personal information is limited to a number of personnel who require such information to fulfill the purchased order. Physically, documents are shipped to you via delivery companies, the United States Postal Service, or electronically, including through online storage platforms or email.<br/><br/>
            Unfortunately, no data transmission can be guaranteed to be 100% secure. Therefore, please note that we cannot guarantee an absolute security of information you transmit and that you provide such information at your own risk. If you believe that your interaction with us is no longer secure, please contact us immediately.
            </p>
            <h3 className="py-8 text-xl sm:text-2xl text-black font-bold">Your Rights</h3>
            <p className="text-lg text-gray-500">Upon a request (subject to identity verification), we will provide you with information about whether we hold any information related to you. Again, upon verifiable request (subject to the standards of the applicable law), you can correct, rectify and delete your personal information, or withdraw your consent on processing your personal information altogether. Yet, please note that if you opt to delete information or withdraw your consent, you may not receive full functionality from our services. Also, we may be required to retain your personal information by law in certain circumstances. Therefore, we may not accommodate a request to change/delete information if we believe the action would violate any law or legal requirement.<br/><br/>
            We often send promotional emails and newsletters from time to time to our consumers who have provided us with their email address.  You can opt-out of promotional communications by using the “Unsubscribe” link and following the unsubscribe instructions in an email you receive from us or by emailing us.<br/><br/>
            If you would like to submit a request about your personal information, you may do so by sending your request by email at <a href='mailto:info@registate.com' className="text-blue-600 font-bold">info@registate.com</a> Following your submission, you may be asked to verify your email address and may also be asked to provide additional information in order to verify your identity.
            </p>
            <h3 className="py-8 text-xl sm:text-2xl text-black font-bold">Minors</h3>
            <p className="text-lg text-gray-500">Our Services are not directed to individuals under the age of eighteen (18), and we do not collect personal information from such individuals knowingly. We kindly request you not to provide us with personal information of such individuals. If you are under the age of eighteen (18), please do not provide any information or cease your activities with this website.</p>
            <h3 className="py-8 text-xl sm:text-2xl text-black font-bold">Information for California Residents</h3>
            <p className="text-lg text-gray-500">If you are a resident of California, you may request from us (subject to a verifiable request) to access certain information. Subject to certain limitations under the applicable California law, you can ask us to provide (i) specific categories of personal information that we have collected about you (ii) the categories of sources for that information, (iii) the business or commercial purposes for collecting the information, (iv) and the categories of third parties with which the information was shared.<br/><br/>
            If you would like to submit a request, you can submit a request by emailing info@registate.com.Following your submission, you may be asked to verify your email address and may also be asked to provide additional information in order to verify your identity. Please note that consistent with California law, we will be unable to satisfy your request until we have verified your identity.<br/><br/>
            We, Registate, do not and will not sell personal information to any third parties.
            </p>
            <h3 className="py-8 text-xl sm:text-2xl text-black font-bold">Information for the European Union (EU) Residents</h3>
            <p className="text-lg text-gray-500">The General Data Protection Regulation (GDPR) by the EU improves EU residents’ personal information protection and allows them to have greater control over their information. We strive to make the best effort to comply with the rules of the GDPR.</p>
            <h3 className="py-8 text-xl sm:text-2xl text-black font-bold">Changes to Our Policies</h3>
            <p className="text-lg text-gray-500">We may update this Policy from time to time to reflect changes in our practices. If we make any material changes, a notice will be posted on this page along with the updated Policy prior to the change becoming effective.</p>
            <h3 className="py-8 text-xl sm:text-2xl text-black font-bold">Contact</h3>
            <p className="text-lg text-gray-500">If you have questions or concerns regarding this Policy or wish to exercise any of your rights listed in this Policy, you can reach us via at<br/><br/>
            <a href='mailto:info@registate.com' className="text-blue-600 font-bold">info@registate.com</a> 
            </p>
        </div>
    )
}
