name: REGISTATE DEV

on:
  push:
    branches: [ dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build-rs-web:
    runs-on: ubuntu-latest
    env:
      S3_LOCATION : ${{ vars.S3_LOCATION_DEV }}
      API_ROOT: ${{ vars.API_ROOT_DEV }}
      APP_ROOT: ${{ vars.APP_ROOT_DEV }}
      AWS_ACCESS_KEY_ID: ${{ secrets.S3_UPLOADER_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_UPLOADER_AWS_SECRET_KEY }}
      CLOUDFRONT_ID: ${{ vars.CLOUDFRONT_DEV }}
      
    steps:
      - uses: actions/checkout@v3
      - name: build
        run: |
          rm -rf build node_modules
          npm install --force
          CI=false npm run build
          cd build
          cat > config.js << EOF
          window.ob = {};
          window.ob.config = { 
              apiRoot: "${API_ROOT}",
              appRoot: "${APP_ROOT}"
          };
          EOF
          /usr/local/bin/aws --region eu-central-1 s3 sync . $S3_LOCATION
          /usr/local/bin/aws --region eu-central-1 cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths "/*"
      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "@elda bhdev rsweb-sync"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.OPERATIONS_SLACK_WEBHOOK_URL }}
 
