name: rs-web

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build-rs-web:
    runs-on: ubuntu-latest
    env:
      S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
      AWS_ACCESS_KEY_ID: ${{ secrets.S3_UPLOADER_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_UPLOADER_AWS_SECRET_KEY }}
      
    steps:
      - uses: actions/checkout@v3
      - name: build
        run: |
          rm -rf build node_modules
          npm install --force
          CI=false npm run build
          cd out

          /usr/local/bin/aws --region eu-central-1 s3 sync . $S3_BUCKET_NAME
